# sqsshd configuration
# See README for all directives

Port 22
HostKey /etc/sqssh/host_key
AuthMode whitelist+user
AuthorizedKeysFile .sqssh/authorized_keys
MaxSessions 64
MaxAuthTries 6
ControlSocket /var/run/sqssh/control.sock
ConnectionMigration yes
PrintMotd yes
PrintLastLog yes
# Banner /etc/sqssh/banner
# AllowUsers
# DenyUsers
